version: 2.1
parameters:
  aws-region:
    default: AWS_REGION_ENV_VAR_NAME
    description: |
      Env var of AWS region to operate in
      (defaults to AWS_DEFAULT_REGION)
    type: env_var_name
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - aws-cli/configure:
          aws-region: << parameters.aws-region >>
          configure-default-region: << parameters.configure-default-region >>
      
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            sudo npm install
         
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
        
      - run:
          name: Deploy application
          command: sls deploy --stage pre
