version: 2

workflows:
   build_and_push_image:
     jobs:
      - aws-ecr/build_and_push_image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          context: myContext #if you are using contexts
          region: AWS_REGION_ENV_VAR_NAME
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            sudo npm install
         
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
        
      - run:
          name: Deploy application
          command: sls deploy --stage pre
